Fix contact us
cooperativa-tech/fkwl pull request #7
Opened 2019-10-25 22:14 UTC by jfranciscosousa

Add i18n suppport.

2019-10-26 23:48 UTC, fmmricardo requested changes

2019-10-26 23:48 UTC, fmmricardo commented on src/i18n/pt.js
> +  contactUs: 'Contact-nos',
Typo on the Pt version.

```suggestion
  contactUs: 'Contacta-nos',
```

2019-10-27 01:38 UTC, jfranciscosousa commented on src/i18n/pt.js
> +  contactUs: 'Contact-nos',
:pray:

2019-10-27 15:59 UTC, fmmricardo approved these changes
🚀

2019-10-28 11:02 UTC, merged